In [2]:
import numpy as np
import quadpy

In [36]:
kronrod_n = 5
kronrod_rule = quadpy.c1.gauss_kronrod(kronrod_n, )
kronrod_qx = kronrod_rule.points
kronrod_qw = kronrod_rule.weights
gauss_rule = quadpy.c1.gauss_legendre(kronrod_n)
gauss_qx = gauss_rule.points
kronrod_qw_gauss = gauss_rule.weights
np.testing.assert_allclose(gauss_qx, kronrod_qx[1::2], atol=1e-10)
kronrod_qx.shape[0], kronrod_qx, kronrod_qw, kronrod_qw_gauss

(11,
 array([-9.84085360e-01, -9.06179846e-01, -7.54166727e-01, -5.38469310e-01,
        -2.79630413e-01, -3.33066907e-16,  2.79630413e-01,  5.38469310e-01,
         7.54166727e-01,  9.06179846e-01,  9.84085360e-01]),
 array([0.04258204, 0.11523332, 0.1868008 , 0.24104034, 0.2728498 ,
        0.28298742, 0.2728498 , 0.24104034, 0.1868008 , 0.11523332,
        0.04258204]),
 array([0.23692689, 0.47862867, 0.56888889, 0.47862867, 0.23692689]))

In [37]:
A = 4
f = lambda x: np.cos(A*x)
true = np.sin(A) / A - np.sin(-A) / A
est1 = 0
est2 = 0
for i in range(kronrod_qx.shape[0]):
    est1 += f(kronrod_qx[i]) * kronrod_qw[i]
    est2 += f(kronrod_qx[i]) * (kronrod_qw_gauss[i//2] if i % 2 == 1 else 0)
print(est1, est2, est1-est2, est1-true, est2-true)

-0.3784012476612154 -0.37779512920215175 -0.0006061184590636648 -7.251255151885516e-12 0.0006061184518124096
