The classical free term coefficient for a smooth surface is either 0.5 or -0.5, depending on whether we are evaluating from the interior or the exterior. But with a halfspace surface, the free term can end up being either 0 or 1. The integrations below demonstrate this fact.

In [8]:
import numpy as np
import sympy as sp
from tectosaur2 import gauss_rule, refine_surfaces, integrate_term
from tectosaur2.laplace2d import double_layer
from tectosaur2.elastic2d import elastic_t

qx, qw = gauss_rule(12)
t = sp.var("t")
circle = refine_surfaces(
    [(t, sp.cos(sp.pi * t), sp.sin(sp.pi * t))], (qx, qw), max_curvature=0.125
)
A = integrate_term(double_layer, circle.pts, circle)
print(A[:, 0, :, 0].sum(axis=1)[0])
A2 = integrate_term(double_layer, circle.pts, circle, limit_direction=-1)
print(A2[:, 0, :, 0].sum(axis=1)[0])

line = refine_surfaces(
    [(t, 100 * t, 0.0 * t)],
    (qx, qw),
    control_points=np.array([[0, 0, 100, 1]]),
)
A3 = integrate_term(
    double_layer, line.pts, line, singularities=np.array([[-100, 0], [100, 0]])
)
print(A3[:, 0, :, 0].sum(axis=1)[A3.shape[0] // 2])
A4 = integrate_term(
    double_layer,
    line.pts,
    line,
    limit_direction=-1,
    singularities=np.array([[-100, 0], [100, 0]]),
)
print(A4[:, 0, :, 0].sum(axis=1)[A3.shape[0] // 2])


-0.9999999999999523
-1.687538997430238e-14


/Users/tbent/Dropbox/active/eq/tectosaur2/tectosaur2/integrate.py:174: UserWarning: Some integrals failed to converge during adaptive integration. This an indication of a problem in either the integration or the problem formulation.
  warnings.warn(


-0.5000000000000002
0.5000000000000002


In [9]:
qx, qw = gauss_rule(12)
t = sp.var("t")
circle = refine_surfaces(
    [(t, sp.cos(sp.pi * t), sp.sin(sp.pi * t))], (qx, qw), max_curvature=0.125
)
A = integrate_term(elastic_t(0.25), circle.pts, circle)
print(A[:, :, :, :].sum(axis=2)[0])
A2 = integrate_term(elastic_t(0.25), circle.pts, circle, limit_direction=-1)
print(A2[:, :, :, :].sum(axis=2)[0])

line = refine_surfaces(
    [(t, 100 * t, 0.0 * t)], (qx, qw), control_points=np.array([[0, 0, 100, 1]])
)
A3 = integrate_term(
    elastic_t(0.25),
    line.pts,
    line,
    singularities=np.array([[-100, 0], [100, 0]]),
)
print(A3[:, :, :, :].sum(axis=2)[A3.shape[0] // 2])
A4 = integrate_term(
    elastic_t(0.25),
    line.pts,
    line,
    singularities=np.array([[-100, 0], [100, 0]]),
    limit_direction=-1,
)
print(A4[:, :, :, :].sum(axis=2)[A3.shape[0] // 2])


[[-1.00000000e+00 -4.98212582e-15]
 [ 3.46944695e-16 -1.00000000e+00]]
[[-2.88380431e-14 -5.15559817e-15]
 [-5.00988140e-15 -9.43689571e-15]]


/Users/tbent/Dropbox/active/eq/tectosaur2/tectosaur2/integrate.py:180: UserWarning: Some expanded integrals reached maximum expansion order. These integrals may be inaccurate.
  warnings.warn(


[[-5.00000000e-01  7.64249014e-06]
 [-7.64249014e-06 -5.00000000e-01]]
[[ 5.00000000e-01  7.64249014e-06]
 [-7.64249014e-06  5.00000000e-01]]
